server:
  servlet:
    encoding:
      force-response: true

spring:
  config:
    import: application-secret.properties
    activate:
      on-profile: local
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/testdb
    username: sa
    password:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    defer-datasource-initialization: true
  web:
    resources:
      static-locations: classpath:/static/

  sql:
    init:
      mode: always
  
